steps:
- name: 'gcr.io/cloud-builders/mvn'
  args: ['-Dmaven.repo.local=/workspace/m2_repository','package']
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/firstkubernetes-176201/spring-clinic', '.']
images: ['gcr.io/firstkubernetes-176201/spring-clinic', 'gcr.io/firstkubernetes-176201/spring-clinic:latest']

